//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(schema_name = "public", table_name = "countries")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub country_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub currency_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub country_code: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
